<a href="https://colab.research.google.com/github/Monochrome901/BCS_project_work/blob/main/temsorflow_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import tensorflow as tf
 print(tf.__version__)

2.8.2


In [ ]:
#create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#number of dimensions in of a tensor
scalar.ndim

0

In [ ]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#dimension of vector
vector.ndim

1

In [ ]:
#creating a matrix
matrix=tf.constant([[1,2],[2,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#datatype defined
another_matrix=tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#lets create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#creating tensors with variable
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#trying .assign
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#creating random tensors
random_1=tf.random.Generator.from_seed(42) #sets the seed of reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal((3,2))

#are they equal?
random_1,random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
#shuffling order of elements in a tensor
not_shuffled=tf.constant([[10,7],[2,3],[4,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [10,  7],
       [ 2,  3]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) #operation level randon seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 4,  5]], dtype=int32)>

In [ ]:
 tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A= np.arange(1,25,dtype=np.int32)
numpy_A
#x=tf.constant(some_matrix)
#y=tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A= tf.constant(numpy_A,shape=(3,8))
B= tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
#getting information from tensors
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim,rank_4_tensor.shape,tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#various attributes of tensor
print("datatypeof every element:", rank_4_tensor.dtype)
print("number of dimensions:", rank_4_tensor.ndim)
print("shape of tensor", rank_4_tensor.shape)
print("elements along the 0 axis", rank_4_tensor.shape[0])
print("elements along last axis", rank_4_tensor.shape[0])
print("total number of elements in our tensor:", tf.size(rank_4_tensor))

datatypeof every element: <dtype: 'float32'>
number of dimensions: 4
shape of tensor (2, 3, 4, 5)
elements along the 0 axis 2
elements along last axis 2
total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
# get the first 2 elements of es=ach dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first element from each dimension drom each index except the final one
rank_4_tensor[:2,:1,:2,:1]

<tf.Tensor: shape=(2, 1, 2, 1), dtype=float32, numpy=
array([[[[0.],
         [0.]]],


       [[[0.],
         [0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor(2 dimension)
rank_2_tensor=tf.constant([[1,2,3],[4,5,6],[6,7,8]])
rank_2_tensor,rank_2_tensor.ndim,rank_2_tensor.shape

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]], dtype=int32)>, 2, TensorShape([3, 3]))

In [ ]:
#get the last item of each row of our tensor
rank_2_tensor.shape[-1],rank_2_tensor[:,-1]

(3, <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 8], dtype=int32)>)

In [ ]:
#adding dimension to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[6],
        [7],
        [8]]], dtype=int32)>

In [ ]:
#alternate to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=0) #'1' means expands final axis

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1) #expand 0-axis

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[6],
        [7],
        [8]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[6, 7, 8]]], dtype=int32)>

In [ ]:
#manipulating tensors
#basic operations
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tf.multiply(tensor,10) #built in function

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#matrix operations
tf.matmul(tensor,tensor),tensor*tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]], dtype=int32)>)

In [ ]:
X=tf.constant([[1,2],[2,3],[3,4]])
Y=tf.constant([[4,5],[5,6],[6,7]])


In [ ]:
#reshaping Y for matrix multiplication
Z=tf.reshape(Y,shape=(2,3))

In [ ]:
tf.matmul(X,Z)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 17, 19],
       [26, 28, 31],
       [36, 39, 43]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 31],
       [51, 61]], dtype=int32)>

In [ ]:
#using transpose
tf.transpose(X), tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 2],
        [3, 3, 4]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 38],
       [47, 56]], dtype=int32)>

In [ ]:
#perform matrix multiplication b/w X and Y(transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 38],
       [47, 56]], dtype=int32)>

In [ ]:
#perform matrix multiplication b/w X and Y(reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 17, 19],
       [26, 28, 31],
       [36, 39, 43]], dtype=int32)>

In [ ]:
#check the value of Y,reshape Y and ransposed Y
print("normal Y:")
print(Y,"\n")
print("y reshape to (2,3")
print(tf.reshape(Y,shape=(2,3)))
print("Y transposed")
print(tf.transpose(Y))

normal Y:
tf.Tensor(
[[4 5]
 [5 6]
 [6 7]], shape=(3, 2), dtype=int32) 

y reshape to (2,3
tf.Tensor(
[[4 5 5]
 [6 6 7]], shape=(2, 3), dtype=int32)
Y transposed
tf.Tensor(
[[4 5 6]
 [5 6 7]], shape=(2, 3), dtype=int32)


In [ ]:
#changing the datatype of a tensor
B=tf.constant([3.1,1.2])
B.dtype

tf.float32

In [ ]:
C=tf.constant([1,3])
C.dtype

tf.int32

In [ ]:
#change from float32 to float16
D=tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3.1, 1.2], dtype=float16)>,
 tf.float16)

In [ ]:
#change int32 to float32
E=tf.cast(C,dtype=tf.float32)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 3.], dtype=float32)>,
 tf.float32)

In [ ]:
#aggregating tensors
#getting absolute values
D=tf.constant([-2,-3])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -3], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [ ]:
#create a random tensor with value  b/w 0 to 100 of size 50
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([73, 46,  3, 19, 67, 78, 16, 66, 91,  9, 61,  7, 13,  3, 18, 41, 29,
       46, 65, 76, 30, 61, 27, 89, 98, 52, 84, 46, 23, 62, 30, 50, 16, 44,
       33, 46, 52, 76, 12, 60, 74,  6, 52, 62, 91, 62, 99, 10, 74, 98])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#finding minimum of tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
#finding maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#finding mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
#finding the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2446>

In [ ]:
tf.reduce_sum((E-tf.reduce_mean(E))*(E-tf.reduce_mean(E)))/100

<tf.Tensor: shape=(), dtype=float64, numpy=399.68>

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=799>

In [ ]:
#finding standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))
#type error to be changed by looking into documents

<tf.Tensor: shape=(), dtype=float32, numpy=28.257982>

In [ ]:
#positional maximum and minimum
#create a new tensor to find positional min and max
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)#positional max

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)],tf.reduce_max(F)==F[tf.argmax(F)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
#squeezing a tensor
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

In [ ]:
#one hot encoding
#create a list of indices
some_list=[0,1,2,3]#could be red,blue,green,yellow
#one hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo", off_value="hi")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo', b'hi', b'hi', b'hi'],
       [b'hi', b'yo', b'hi', b'hi'],
       [b'hi', b'hi', b'yo', b'hi'],
       [b'hi', b'hi', b'hi', b'yo']], dtype=object)>

In [ ]:
#squaring,log and sqrt
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
#tensors and numpy
J=tf.constant(np.array([2.,3.,4.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [ ]:
np.array(J), type(np.array(J))

(array([2., 3., 4.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([2., 3., 4.]), numpy.ndarray)

In [ ]:
#defaults type of each are slightly different
numpy_J=tf.constant(np.array([1.,2.,3.]))
tensor_J=tf.constant([3.,4.,5.])
#checking datatypes of both
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)